services:
  # PostgreSQL Database
  db:
    build:
      context: ./postgress
      dockerfile: Postgress.Dockerfile
    container_name: users_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    container_name: backend_app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./backend:/app

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    container_name: frontend_app
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    networks:
      - app_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
